# ARITHMETIC

In [1]:
import numpy as np
var = np.array([1,2,3,4])

varadd = var+3
print(varadd)

[4 5 6 7]


In [3]:
import numpy as np
var1 = np.array([1,3,5,9])
var2 = np.array([2,3,8,0])
varadd = var1+var2
print(varadd)

[ 3  6 13  9]


In [4]:
import numpy as np
var1 = np.array([2,3,5,8])
varmul = var1*5
print(varmul)


[10 15 25 40]


In [5]:
import numpy as np
var5 = np.array([2,87,4,3,67])
varmod = var5 % 4
print(varmod)

[2 3 0 3 3]


In [6]:
import numpy as np
var1 = ([5,3,7,9])
varrec = np.reciprocal(var1)
print(varrec)

[0 0 0 0]


# 2D ARRAY