In [1]:
import numpy as np
x= np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [2]:
import numpy as np
x=[1,2,3,4]
y=np.array(x)
print(type(y)) 

<class 'numpy.ndarray'>


In [5]:
 l = []
    
for i in range(1,5):
    int_1= int(input("enter:"))
    l.append(int_1)
    
print(np.array(l))

enter:6
enter:7
enter:4
enter:4
[6 7 4 4]


In [6]:
ar2 = np.array([[1,2,3,4,],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [ ]:
import numpy as np
ar_zero=np.zeros(4)
print(ar_zero)

In [8]:
# ones
import numpy as np
ar_one = np.ones(4)
print(ar_one)



[1. 1. 1. 1.]


In [10]:
import numpy as np
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [11]:
import numpy as np
ar_dia = np.eye(5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
import numpy as np
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [3]:

import numpy as np


In [4]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,0]
my_lst3 = [3,5,2,7,8]

In [5]:
arr = np.array([my_lst1, my_lst2, my_lst3])

In [6]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [3, 5, 2, 7, 8]])

In [7]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 3, 5],
       [2, 7, 8]])

In [8]:
arr[:,3:]

array([[4, 5],
       [9, 0],
       [7, 8]])

In [9]:
##copy functions and broadcasting

In [19]:
arr1 = arr

In [20]:
arr1[3:]= 500

In [21]:
print(arr1)

[[  1   2   3 500 500]
 [  6   7   8 500 500]
 [  3   5   2 500 500]]


In [22]:
np.ones(4,dtype=float)

array([1., 1., 1., 1.])