In [2]:
import numpy as np

var = np.random.rand(7)
print(var)


[0.60940687 0.36756757 0.05264117 0.52050051 0.46035811 0.55796216
 0.88980304]


In [3]:
import numpy as np

var1 = np.random.rand(2,5)
print(var1)

[[0.64639149 0.09148385 0.66236566 0.57097669 0.25471476]
 [0.87096397 0.30087982 0.807707   0.2102907  0.640236  ]]


In [4]:
import numpy as np
var2 = np.random.randn(2,2)
print(var2)

[[-0.38080052 -1.20232204]
 [-1.25188823 -0.15973715]]


In [8]:
import numpy as np
#np.random.randint(min,max,total val)
var3 = np.random.randint(5,20,4)
print(var3)

[19  7 13  7]
